### PR TITLE
Retina support

### PR DESCRIPTION
**Pull request by yohanboniface**
Anyone for a review / test? :)

cc @nebulon42 @kent1D

### CODE REVIEW

**Comment by kent1D** [comment]
For the review, I don't think I can do something ;)

But I just tested

Here is a test non retina vs retina :
kosmtik_non_retina_vs_retina

And here the retina vs retina :

kosmtik_retina_vs_retina

On my retina screen, it loads directly @2x, on my non retina screen the normal scale.

I had nothing to do, is it right?

**Comment by kent1D** [comment]
Mmmh I has a bug maybe zooming too quickly 

kosmtik_retina_bug_zoom6

I had to close kosmtik and relaunch it to solve the problem

**Comment by kent1D** [comment]
Ok the bug appears in this use case.

2 screens for my computer, one in retina, the other not.

Charging the map on one of them.

Charging the map on the other.

The second one freeze.

Need to click on reload to reload the tiles

**Comment by nebulon42** [comment]
ATM I don't have a retina display available. How does it detect if it needs retina or not?
Is there the need for a separate map pool?

**Comment by yohanboniface** [comment]
> How does it detect if it needs retina or not?

This is the browser that actually decides to ask for retina tiles (handled by Leaflet directly, see `{r}` parameter).

> Is there the need for a separate map pool?

Yes, because the map itself needs a scale x2

**Comment by MattBlissett** [comment]
I'm only running this using the Docker setup in https://github.com/gravitystorm/openstreetmap-carto/, which I've changed:

```diff
-RUN npm install -g kosmtik
+RUN npm install -g git://github.com/kosmtik/kosmtik.git#retina
```
Switching between map pools, in my case by using "Responsive Design Mode" on Firefox developer tools and refreshing the page, causes kent1D's problem when going from 1→2, and when going from 2→1 a similar problem with tiles showing the wrong data:

screenshot_20180515_231343

I'd guess some variables are shared between the two pools, but shouldn't be.

**Comment by yohanboniface** [comment]
Thanks @MattBlissett for pointing me to a way to reproduce!

(Yeah, two months later, I know… ;) )

**Pull request merged**
