### PR TITLE
Adds support for specifying the name of the style used

### PR DESCRIPTION
**Pull request by undying**
If there are many styles in one folder and you need to run several kosmtik instances, then you can now specify its name for each style.

### CODE REVIEW

**Comment by undying** [comment]
Have failed test, but actually have no idea why:
1. rendering code didn't change;
2. resulting tiles looks similar but binary have difference.

Screenshot 2024-02-21 at 10 27 55

**Comment by yohanboniface** [comment]
Hey @undying seems your initial change is missing from the PR now, I only see the test image in the diff. :/

**Comment by undying** [comment]
Hello!
There are three commits and the initial change is [here](https://github.com/kosmtik/kosmtik/pull/351/commits/94c00bef7c0f1aeecb6c68f03907f68bb2615521).
The rest was for sync with original repository and test data update.

**Comment by pnorman** [comment]
There are no changes in this PR except the test image - can you rebase it? That would make it clearer what the changes are.

**Comment by undying** [comment]
I'm sorry. I've checked the repository, and it seems that these changes are already merged. So I'm closing this PR.
Thank you!

**Pull request closed without merging**
