### PR TITLE
specify npm >= 1.5.0 as required 

### PR DESCRIPTION
**Pull request by nebulon42**
Necessary for handling scoped packages like carto.
Ref #215.

### CODE REVIEW

**Comment by pnorman** [comment]
Does this mean we're dropping Debian testing support, as it has npm 1.4.21?

**Comment by yohanboniface** [comment]
Quite hard to combine NodeJS policy (bump version every rainy morning) and Debian one (bump version on leap years only).

As I see it, the situation is:
- Mapbox decided to move Carto to "mapbox" namespace (actually "scope" but they use it as namespace)
- npm only support scoped packages since 1.5
- kosmtik depends on npm

So I think we don't have a lot of options, sadly.

**Comment by pnorman** [comment]
> So I think we don't have a lot of options, sadly.

The diff I have so I can continue use Kosmtik is

```diff
diff --git a/package.json b/package.json
index e0eaa77..54f11c8 100644
--- a/package.json
+++ b/package.json
@@ -23,7 +23,7 @@
     "npm": ">=1.5.0"
   },
   "dependencies": {
-    "@mapbox/carto": "^0.16.1",
+    "carto": "^0.16.1",
     "generic-pool": "^3.1.6",
     "js-yaml": "^3.4.2",
     "json-localizer": "0.0.3",
diff --git a/src/back/renderer/Carto.js b/src/back/renderer/Carto.js
index c44e3b9..07fdc3f 100644
--- a/src/back/renderer/Carto.js
+++ b/src/back/renderer/Carto.js
@@ -1,4 +1,4 @@
-var carto = require('@mapbox/carto');
+var carto = require('carto');


 var Carto = function (project) {
```

**Comment by nebulon42** [comment]
@pnorman Why don't you upgrade npm? It can even be done with npm itself. See https://docs.npmjs.com/getting-started/installing-node#updating-npm

**Comment by pnorman** [comment]
> @pnorman Why don't you upgrade npm? It can even be done with npm itself. See https://docs.npmjs.com/getting-started/installing-node#updating-npm

I don't let NPM do stuff as root or muck around with global stuff.

**Comment by yohanboniface** [comment]
> I don't let NPM do stuff as root or muck around with global stuff.

I follow the same rule. 

> The diff I have so I can continue use Kosmtik is

Oh, so that means that we can continue using "carto" even if it has a scope? I guess this will work until there will be another "carto" package. But we may take the risk. @nebulon42 what do you think?

**Comment by nebulon42** [comment]
Understandable. But then, if you also don't want to install a newer node version from another package source, I think I can't help you there.

> Oh, so that means that we can continue using "carto" even if it has a scope?

The old releases are of course still there, but are marked as deprecated. But I will be releasing 0.17 soon hopefully and that will be only available as scoped package. So I don't want to get stuck with outdated versions of carto for some 2.5 years old npm. Especially as I have fixed some long standing bugs in the current master.

**Pull request merged**
