### PR TITLE
Use Javascript class syntax

### PR DESCRIPTION
**Pull request by hiddewie**
*Preview the diff with whitespace disabled!* [direct link](https://github.com/kosmtik/kosmtik/pull/319/files?diff=split&w=1) 

### This PR

Cleans up the definition of backend classes massively, by using the Javascript `class` syntax. This allows:
- `class A` instead of `.prototype`
- `constructor` and `super` instead of static calls to parent prototypes.
- `A extends B` instead of `util.extends(...)`

### CODE REVIEW

**Comment by yohanboniface** [comment]
Thanks a lot for this work!
Can you also have a look at plugins that would inherit from core classes ? From the top of my head I can remember kosmtik-tiles-export and kosmtik-mbtiles-export at least.

Otherwise I'll have a look myself, but I'm a bit in a rush there days :(

**Comment by hiddewie** [comment]
@yohanboniface Yes, definitely. It would be nice to also have the plugins up-to-date considering the code style. I will make some PRs in those plugin repos.

After that, it would be nice to have NPM releases to let users (also see #309) without intimate Javascript/NodeJS knowledge install the package using the instructions in the readme.

**Comment by hiddewie** [comment]
@yohanboniface I went through the entire list of plugins, and updated the (backend) code to the class syntax whereever possible.

**Comment by yohanboniface** [comment]
Fantastic work, thanks!

**Comment by yohanboniface** [comment]
> After that, it would be nice to have NPM releases to let users (also see #309) without intimate Javascript/NodeJS knowledge install the package using the instructions in the readme.

Sure! Missing time to do it right away, I'll try next week, same for Travis :s

**Pull request merged**
