### PR TITLE
upgrade node-mapnik to 3.6.2

### PR DESCRIPTION
**Pull request by nebulon42**
ref https://github.com/mapbox/carto/issues/484

### CODE REVIEW

**Comment by nebulon42** [comment]
Ah, we already had the test failure. I forgot. :(

**Comment by yohanboniface** [comment]
Looking at the failures, it seems linked to the upgrade of Mapnik: seems the polygon coordinates order has shifted by one.
Tempted to say it safe to merge, after fixing the test fixtures according to new Mapnik.

**Comment by yohanboniface** [comment]
@nebulon42 see https://github.com/kosmtik/kosmtik/commit/5f3511b1ce1fb201b7b897f6d7f7f21ae2dcd909

Each time we upgrade mapnik, we need to update the test data.

I could do this myself, but the branch is on your repo ;)

**Comment by nebulon42** [comment]
Sorry, seemingly I don't understand everything of it. I have push the branch here, so that you can take it on from here. :)

**Pull request closed without merging**
